name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  ECR_REGION: us-east-1
  ECR_REPOSITORY: niluxsi-repo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.ECR_REGION }}

      - name: Build and Push Docker Image
        env:
          ECR_REGISTRY: ${{ env.ECR_REPOSITORY }}
          IMAGE_TAG: v0.1
      - name: Login to AWS ECR
        id: login
        run: aws ecr get-login-password --region $ECR_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY

      - name: Build and Push Docker Image
        run: |
          docker build -t $ECR_REGISTRY:$IMAGE_TAG .
          docker push $ECR_REGISTRY:$IMAGE_TAG
